version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
  web:
    build: .
    volumes:
      - .:/app
      - /log # persist logs
    depends_on:
      - db
    #environment:
      #RAILS_ENV: 'production'
      #RACK_ENV: 'production'